### PR TITLE
feat: enable batch training of files from a directory.

### PR DESCRIPTION
**Pull request by silva-fabio**
This PR enable batch training of files from a directory running the easy colab.

 - The original behavior has been preserved
 - 3 parameters were added:
    -   training_directory: directory with the files to be trained 
    -  include_files: A regex or sequence of regex patterns separated by comma for files to include in the training.
                           Defaults to None, which includes all files.
     - exclude_files: A regex or sequence of regex patterns separated by comma for files to exclude from the training. 
                           Defaults to None, which excludes no files.
 - Models are exported using the corresponding file name and the associated training plot are also saved in the same exported version folder
 
Usage Examples:

1 - Files in the root directory.  If the files are in the root directory, use `training_directory="."`

Screenshot 2023-04-22 at 16 49 06

2 - Files in a directory. For instance: `training_directory="training_files"`

Screenshot 2023-04-22 at 22 26 39

3 - Filtering using include files. For instance:` include_files="Boss" `

Screenshot 2023-04-22 at 21 58 11

4 - Filtering using include file. For instance:` include_files="Boss,Vox-AC15CH-Crunch-Normal"`

Screenshot 2023-04-22 at 21 25 13

5 - Filtering using exclude files. For instance: `exclude_files="Boss" `

Screenshot 2023-04-22 at 22 05 45

6 - Filtering using include and exclude files. For instance:  `include_files="Boss,Vox-AC15CH-Crunch-Normal", exclude_files="BossMT2_01" `

Screenshot 2023-04-22 at 22 12 36

7 - Using a little more advanced regex:

Screenshot 2023-04-22 at 22 19 00

### CODE REVIEW

**Comment by sdatkinson** [comment]
Thanks for the PR :)

Unfortunately, there's an issue with this: [Colab is meant for interactive use](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions) and will time out on batches that are too large. I'm aware that paid versions of Colab allow you to bypass this, but I want `easy_colab.ipynb` to be the most accessible way to train NAM models, and that means prioritizing the free tier of Colab/helping new users avoid pitfalls like having their session hang up on them. So, I'm not really inclined to merge this PR to the main repo.

**Comment by silva-fabio** [comment]
Hi @sdatkinson, thanks for your feedback. 

I understand your concerns regarding potential disconnection issues using the free Colab version. To address this, we can include a Warning message that advises users to exercise caution when using this feature in the free Colab version to avoid the risk of losing trained models and also label it as "Experimental". It's important to note, however, that there are no such limitations on local training or even if the user uses the paid version of Colab.

I have personally tested batch training with 5 to 10 files (with 100 epochs each) without encountering no major issues thus far in the free Colab, but I totally agree that the free version has limitations on the number of epochs that can be run in total, maybe something around 1000 epochs should be Ok to use. We can mention this limitation to users to ensure they can make informed decisions about how to use this feature.

It is possible that in the future, local training may become more popular for this type of application. As you may know, guitar players are always on the lookout for new gear, and many may be inclined to add a more powerful GPU to their machines. Currently, I prefer to train locally on my M1, which allows me to achieve decent results letting it run overnight. 

Also, from a user's perspective, this feature could prove to be very useful, particularly for those who frequently undertake heavy training. It may be worthwhile to reach out to some of these users and ask whether they find this type of feature compelling.  It is quite common for users to share models for the same amp with different settings, and this feature could significantly reduce the effort required in managing these trainings.

If you change your mind but come across any issues with the code, please let me know, and I will take the necessary steps to address them.

**Comment by sdatkinson** [comment]
> It's important to note, however, that there are no such limitations on local training or even if the user uses the paid version of Colab.

The primary intended use case for `easy_colab.ipynb` is meant to be the free tier of Colab.

> We can mention this limitation to users to ensure they can make informed decisions about how to use this feature.

Even though that sounds good in theory, I know from my experience so far that I'll get a lot of questions & complaints. The goal is to make it so easy that you don't even need to read the instructions and can still get through it without choosing the wrong thing.

> Also, from a user's perspective, this feature could prove to be very useful, particularly for those who frequently undertake heavy training.

I agree with this 🙂 But I would still like to be mindful of scope and have a clear idea of who I'm building for. With `easy_colab.ipynb`, it's the guitarists who have a really minimal idea of how to use this code and need simplicity above all else.

---

I agree that what you're suggesting is useful, so I don't want to keep you from sharing it with people. But, it also would increase the surface of things that I'd be on the hook to maintain, and I would like to be rather choosy about that. Minding both of those considerations, maybe I'll suggest is that if you'd like to invest your time & effort into making more advanced training tools, you can perhaps start that in a separate repo that builds on top of this one?  I'd be happy to refactor code in here (and take PRs!) if there are changes that would make things more modular and easier to build on top of. This would also help keep the surface of things I need to continue maintaining from growing and becoming unmanageable, given my finite time.

Sound good?

**Comment by sdatkinson** [comment]
Going to be close this as out-of-scope for the repo.

**Pull request closed without merging**
