### PR TITLE
Add a pyproject.toml file.

### PR DESCRIPTION
**Pull request by Justin-Hoffman**
Addresses https://github.com/sdatkinson/neural-amp-modeler/issues/487

Remove setup.py and move to pyproject.toml. 

~Right now this results in duplicate instances of project version ( inside pyproject.toml and inside ./nam/_version.py)
I'm sure there's an elegant way to avoid this, I just haven't done it yet. I wanted to open the MR for feedback as is.~
^ This is addressed in the second commit. 

With this change you can still just 
python3 -m pip install .

Both the workaround for the older transformer/numpy library and test dependencies are expressed as optional dependencies and can be installed with: 
python3 -m pip install .[test] (or .[transformer-compat])

But maybe it's time to remove that workaround?

I haven't addressed the conda environments files, but I propose that we put: 
    - neural-amp-modeler
or possibly:
    - neural-amp-modeler[test]
under the dependencies/pip section and remove the requirements.txt (which is redundant because they are in pyproject.toml now)

The environment files can likely get a de-duplication pass as well.

### CODE REVIEW

**Comment by Justin-Hoffman** [comment]
This addresses: 
https://github.com/sdatkinson/neural-amp-modeler/issues/487

**Comment by Justin-Hoffman** [comment]
I can see and will take a look.

**Comment by Justin-Hoffman** [comment]
This passes a local run of  xvfb-run -a pytest, so I expect this workflow likely will as well (barring any unexpected version related issues).

**Comment by Justin-Hoffman** [comment]
Bumping this @sdatkinson - Let me know if there's anything else you'd like to see here.

**Comment by sdatkinson** [comment]
Sorry for the delay. I've been busy this week. Going to find time in the coming week.

**Review by sdatkinson — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
