### PR TITLE
Add Apple Metal support for faster training on M1/M2

### PR DESCRIPTION
**Pull request by phillipmself**
Works on my M1 mac. I'd like to see some testing in the NAM facebook group to verify it still works on non-silicon machines.

I used the CPU environment yml to configure the environment for this.

### CODE REVIEW

**Comment by ncsolar** [comment]
This patch works on my M1 MBP, I get these two warnings:

`Sanity Checking: 0it [00:00, ?it/s]
/Users/my_user/miniforge3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: 
PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

/Users/my_user/miniforge3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: 
PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.`

**Comment by 2-dor** [comment]
> This patch works on my M1 MBP, but I get these two warnings? :
> 
> `Sanity Checking: 0it [00:00, ?it/s] /Users/my_user/miniforge3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
> 
> /Users/my_user/miniforge3/envs/nam/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument`(try 8 which is the number of cpus on this machine) in the`DataLoader` init to improve performance.`

that warning comes up even when training on Windows PCs with nvidia GPUs - guess it's a pytorch thing. If you hardcode the workers to 8 (in the core.py file) there's a slight pause at the beginning of each epoch basically delaying the training process. Best ignore it.

**Comment by honkkis** [comment]
Yes, confirmed, works very well on M1 MBP. Thanks a lot!

**Review by sdatkinson — APPROVED** [review]
Thanks for your patience! LGTM! 👍🏻

**Comment by sdatkinson** [comment]
Resolves #104

**Comment by phillipmself** [comment]
Thanks!

**Comment by phillipmself** [comment]
@ServusJon I haven't tried running a notebook locally. I just used environment_cpu.yml to configure conda and then ran the nam gui from the command line.

**Comment by ServusJon** [comment]
Ok. But could you do a step by step for me here please. What files to put where? All the commands. Thank you! Am 21.03.2023 um 22:15 schrieb Phillip Self ***@***.***>:﻿
@ServusJon I haven't tried running a notebook locally. I just used environment_cpu.yml to configure conda and then ran the nam gui from the command line.

**Comment by jamsden** [comment]
@phillipmself how did you create the environment on M1 macOS? Using macOS 13.3.1, I get the following error:
```
conda env create -f environment_cpu.yml
...
Collecting onnx
  Using cached onnx-1.13.1-cp311-cp311-macosx_10_12_x86_64.whl (12.7 MB)

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
```

**Comment by jamsden** [comment]
You need to edit environment_cpy.yml and add:
```
dependencies:
  - python==3.10.6
```
before creating the environment.

**Comment by Chrisedmo** [comment]
Actually, I fixed this using this 

> resolved: I added:
> 
> ```
> dependencies:
>   - python==3.10.6
> ```

Added it to 'environment_cpu.yml' and then deleted the NAM folder under anaconda and reran 'conda env create -f environment_cpu.yml' and it works!

**Pull request merged**
